/**
 * context/Web3Context.jsx
 * Manages MetaMask connection, Ethereum provider, and contract interaction.
 * Uses ethers.js v6.
 */

import {
  createContext, useContext, useState, useEffect, useCallback, useMemo
} from "react";
import { ethers } from "ethers";
import toast from "react-hot-toast";

// Contract artifacts generated by the Hardhat deploy script
// (This file is created after running: npm run deploy in /blockchain)
let contractABI     = [];
let contractAddress = import.meta.env.VITE_CONTRACT_ADDRESS || "";

try {
  const data = await import("../contracts/VotingSystem.json");
  contractABI     = data.abi     || data.default?.abi     || [];
  contractAddress = data.address || data.default?.address || contractAddress;
} catch {
  console.warn("VotingSystem.json not found. Run the deploy script first.");
}

const EXPECTED_CHAIN_ID = parseInt(import.meta.env.VITE_CHAIN_ID || "1337");

const Web3Context = createContext(null);

export function Web3Provider({ children }) {
  const [provider,       setProvider]       = useState(null);
  const [signer,         setSigner]         = useState(null);
  const [contract,       setContract]       = useState(null);
  const [walletAddress,  setWalletAddress]  = useState(null);
  const [chainId,        setChainId]        = useState(null);
  const [isConnected,    setIsConnected]    = useState(false);
  const [isConnecting,   setIsConnecting]   = useState(false);
  const [networkError,   setNetworkError]   = useState(null);

  // ── Check if MetaMask is installed ──────────────────────────────────────
  const hasMetaMask = typeof window !== "undefined" && Boolean(window.ethereum);

  // ── Connect MetaMask wallet ──────────────────────────────────────────────
  const connectWallet = useCallback(async () => {
    if (!hasMetaMask) {
      toast.error("MetaMask not detected. Please install the MetaMask extension.");
      return null;
    }

    setIsConnecting(true);
    setNetworkError(null);

    try {
      // Request account access
      const accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      });

      if (!accounts.length) {
        toast.error("No accounts found. Please unlock MetaMask.");
        return null;
      }

      // Build ethers provider from MetaMask's injected provider
      const ethersProvider = new ethers.BrowserProvider(window.ethereum);
      const ethersSigner   = await ethersProvider.getSigner();
      const network        = await ethersProvider.getNetwork();
      const currentChainId = Number(network.chainId);

      // Warn if not on Ganache
      if (currentChainId !== EXPECTED_CHAIN_ID) {
        setNetworkError(
          `Wrong network! Expected chain ID ${EXPECTED_CHAIN_ID} (Ganache), got ${currentChainId}. Switch in MetaMask.`
        );
        toast.error(`Please switch MetaMask to Ganache (chain ID: ${EXPECTED_CHAIN_ID})`);
      }

      // Instantiate the smart contract
      let contractInstance = null;
      if (contractAddress && contractABI.length) {
        contractInstance = new ethers.Contract(
          contractAddress,
          contractABI,
          ethersSigner
        );
      }

      setProvider(ethersProvider);
      setSigner(ethersSigner);
      setContract(contractInstance);
      setWalletAddress(accounts[0]);
      setChainId(currentChainId);
      setIsConnected(true);

      toast.success(`Wallet connected: ${accounts[0].slice(0, 6)}…${accounts[0].slice(-4)}`);
      return accounts[0];
    } catch (err) {
      const msg = err.code === 4001
        ? "Wallet connection rejected by user."
        : err.message || "Failed to connect wallet.";
      toast.error(msg);
      return null;
    } finally {
      setIsConnecting(false);
    }
  }, [hasMetaMask]);

  // ── Disconnect (local state only — MetaMask has no programmatic disconnect) ─
  const disconnectWallet = useCallback(() => {
    setProvider(null);
    setSigner(null);
    setContract(null);
    setWalletAddress(null);
    setChainId(null);
    setIsConnected(false);
    setNetworkError(null);
    toast("Wallet disconnected.", { icon: "🔌" });
  }, []);

  // ── Cast a vote via MetaMask ─────────────────────────────────────────────
  const castVoteOnChain = useCallback(
    async (candidateId) => {
      if (!contract) throw new Error("Contract not initialized. Connect wallet first.");
      if (!signer)   throw new Error("Wallet not connected.");

      toast.loading("Sending vote transaction…", { id: "vote-tx" });

      const tx      = await contract.vote(candidateId);
      toast.loading("Waiting for blockchain confirmation…", { id: "vote-tx" });

      const receipt = await tx.wait(); // wait for 1 confirmation
      toast.dismiss("vote-tx");
      return { txHash: tx.hash, receipt };
    },
    [contract, signer]
  );

  // ── Listen for MetaMask account/chain changes ────────────────────────────
  useEffect(() => {
    if (!window.ethereum) return;

    const handleAccountsChanged = (accounts) => {
      if (accounts.length === 0) {
        disconnectWallet();
      } else {
        setWalletAddress(accounts[0]);
        toast("Account changed — refreshing…", { icon: "🔄" });
      }
    };

    const handleChainChanged = () => {
      // MetaMask recommends reloading on chain change
      window.location.reload();
    };

    window.ethereum.on("accountsChanged", handleAccountsChanged);
    window.ethereum.on("chainChanged",    handleChainChanged);

    return () => {
      window.ethereum.removeListener("accountsChanged", handleAccountsChanged);
      window.ethereum.removeListener("chainChanged",    handleChainChanged);
    };
  }, [disconnectWallet]);

  // ── Auto-reconnect if user previously connected ──────────────────────────
  useEffect(() => {
    const autoConnect = async () => {
      if (!window.ethereum) return;
      try {
        const accounts = await window.ethereum.request({ method: "eth_accounts" });
        if (accounts.length > 0) {
          await connectWallet();
        }
      } catch (_) {}
    };
    autoConnect();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const value = useMemo(() => ({
    provider,
    signer,
    contract,
    walletAddress,
    chainId,
    isConnected,
    isConnecting,
    networkError,
    hasMetaMask,
    contractAddress,
    connectWallet,
    disconnectWallet,
    castVoteOnChain,
  }), [
    provider, signer, contract, walletAddress, chainId, isConnected,
    isConnecting, networkError, hasMetaMask,
    connectWallet, disconnectWallet, castVoteOnChain,
  ]);

  return <Web3Context.Provider value={value}>{children}</Web3Context.Provider>;
}

export const useWeb3 = () => {
  const ctx = useContext(Web3Context);
  if (!ctx) throw new Error("useWeb3 must be used inside <Web3Provider>");
  return ctx;
};